# Generated by Django 3.2.4 on 2021-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_detail',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('zip', models.IntegerField()),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_Json', models.CharField(max_length=5000)),
            ],
        ),
    ]
