# Generated by Django 3.2.4 on 2021-07-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_and_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_detail',
            name='address',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='shipping_detail',
            name='email',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='shipping_detail',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipping_detail',
            name='item_Json',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='shipping_detail',
            name='last_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipping_detail',
            name='mobile_number',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='shipping_detail',
            name='state',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
