# Generated by Django 3.2.4 on 2021-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('product_desc', models.CharField(max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
